
rule sarscov2_test_download_filtered_metadata:
    output:
        metadata=temp("sars-cov-2-nextstrain-2022-2023/data/filtered_metadata.tsv.zst"),
    params:
        metadata_url="https://data.nextstrain.org/files/workflows/cartography/filtered_metadata_2023-06-26.tsv.zst",
    conda: "../cartography.yml"
    shell:
        """
        curl -o {output.metadata} {params.metadata_url}
        """

rule sarscov2_test_prioritize_recombinant_samples:
    input:
        metadata="sars-cov-2-nextstrain-2022-2023/data/filtered_metadata.tsv.zst",
    output:
        priorities="sars-cov-2-nextstrain-2022-2023/data/priorities.tsv",
    conda: "../cartography.yml"
    shell:
        """
        python3 sars-cov-2-nextstrain-2022-2023/scripts/prioritize_recombinants.py \
            --metadata {input.metadata} \
            --output {output.priorities}
        """

rule sarscov2_test_subsample_late_samples:
    input:
        metadata="sars-cov-2-nextstrain-2022-2023/data/filtered_metadata.tsv.zst",
        reference="sars-cov-2-nextstrain-2022-2023/config/reference.txt",
        priorities="sars-cov-2-nextstrain-2022-2023/data/priorities.tsv",
    output:
        strains="sars-cov-2-nextstrain-2022-2023/data/strains.txt",
    conda: "../cartography.yml"
    shell:
        """
        augur filter \
            --metadata {input.metadata} \
            --include {input.reference} \
            --min-date 2022-01-01 \
            --max-date 2023-06-26 \
            --group-by region year month \
            --subsample-max-sequences 2000 \
            --priority {input.priorities} \
            --output-strains {output.strains}
        """

rule sarscov2_test_download_all_aligned_sequences:
    output:
        alignment=temp("sars-cov-2-nextstrain-2022-2023/data/all_aligned.fasta.zst"),
    params:
        alignment_url="https://data.nextstrain.org/files/ncov/open/aligned.fasta.zst",
    conda: "../cartography.yml"
    shell:
        """
        curl -o {output.alignment} {params.alignment_url}
        """

rule sarscov2_test_extract_subsampled_data:
    input:
        metadata="sars-cov-2-nextstrain-2022-2023/data/filtered_metadata.tsv.zst",
        alignment="sars-cov-2-nextstrain-2022-2023/data/all_aligned.fasta.zst",
        strains="sars-cov-2-nextstrain-2022-2023/data/strains.txt",
    output:
        metadata="sars-cov-2-nextstrain-2022-2023/data/metadata.tsv.zst",
        alignment="sars-cov-2-nextstrain-2022-2023/data/aligned.fasta.zst",
    conda: "../cartography.yml"
    shell:
        """
        augur filter \
            --metadata {input.metadata} \
            --sequences {input.alignment} \
            --exclude-all \
            --include {input.strains} \
            --output-metadata {output.metadata} \
            --output-sequences {output.alignment}
        """
