rule all:
    input:
        "cartography.pdf",
        "cartography.html"

rule manuscript_pdf:
    input:
        manuscript = "cartography.md"
    output:
        manuscript = "cartography.pdf"
    conda: "../cartography.yml"
    shell:
        """
        pandoc --citeproc --bibliography=cartography.bib -s {input.manuscript} -o {output.manuscript}
        """

rule manuscript_html:
    input:
        manuscript = "cartography.md"
    output:
        manuscript = "cartography.html"
    conda: "../cartography.yml"
    shell:
        """
        pandoc --citeproc --bibliography=cartography.bib -s {input.manuscript} -o {output.manuscript}
        """
